version: 2
jobs:
  build:
    working_directory: ~/repo
    # The primary container is an instance of the first list image listed. Your {% comment %} TODO: Job {% endcomment %}build commands run in this container.
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Update yarn
          command: 'npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    docker:
      - image: node/node:8.9.4
    steps:
      - checkout
      - run:
          name: make
          command: yarn bsb -make-world
      - run:
          name: Test
          command: yarn coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build